Embeds:
  Welcome:
    Title: "Welkom"
    Description: "Welkom op de Discord server., {user-mention}! \n\n Uitgenodigd door: {inviter-mention}\nTotaal leden: {total}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  Leave:
    Title: "Vaarwel"
    Description: "Vaarwel, {user-mention}! Het was leuk je in de buurt te hebben.... \n\n Totaal leden: {total}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  Shop:
    Title: "🛍️ Serverwinkel (Pagina {current-page}/{max-pages})"
    Description: "Welkom bij de server winkel! Je kunt items uit de winkel kopen door het commando `-buy <item>`."
    Format: ["{item-display}", "{item-description}"]
  CoinTop:
    Title: "👑 Munt Leaderboard (Pagina {current-page}/{max-pages})"
    Footer: "Totaal Ingezamelde Munten: {totalcoins}"
  LevelTop:
    Title: "✨ Niveau Leaderboard (Pagina {current-page}/{max-pages})"
    Footer: "Total XP Collected: {totalxp}"
  Ticket:
    Title: "🎟️ Ticket"
    Description: "Hallo, {user-mention}. Hartelijk dank dat u contact heeft opgenomen met ons support team. We zullen klaar staan om u zo snel mogelijk te helpen. In de tussentijd, gelieve uw problemen zo gedetailleerd mogelijk te beschrijven."
    Footer: "Ticket Systeem"
    Timestamp: true
    Thumbnail: "{bot-pfp}"
    Fields:
      - Name: "Reden"
        Value: "{reason}"
  Announcement:
    Title: "📢 {title}"
    Description: "{description}"
    Footer: "Aankondiging door: {user-tag}"
    Timestamp: true
    FooterIcon: "{user-pfp}"
    AuthorIcon: "{bot-pfp}"
  Update:
    Title: "📰 Update {update-version}"
    Description: "{update}"
    Timestamp: true
    Footer: "Door: {user-tag}"
    FooterIcon: "{user-pfp}"
  Poll:
    Title: "📊 Poll | {question}"
    Description: "{description}"
    Timestamp: true
  Links:
    Title: "🔗 Links"
    Description: "Alle links met betrekking tot de server"
  SuggestionSent:
    Title: "📬 Suggestie verzonden"
    Description: "Bedankt voor de suggestie! Als je het wilt verwijderen, reageer dan op de [suggestion]({link}) met 🗑️"
    Timestamp: true
    Color: "#25de1f"
  PendingSuggestion:
    Title: "Suggestie #{id}"
    Fields:
      - Name: "Suggestie"
        Value: "{suggestion}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "van"
        Value: "{user-mention}"
        Inline: true
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Suggestion:
    Title: "Suggestie #{id} | {status}"
    Fields:
      - Name: "Suggestie"
        Value: "{suggestion}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "van"
        Value: "{user-mention}"
        Inline: true
      - Name: "Reden {status}"
        Value: "{reason}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "Stemmen"
        Value: "**Upvotes:** {upvotes-amount} ({upvotes-percentage})\n**Downvotes:** {downvotes-amount} ({downvotes-percentage})\n**Totaal:** {opinions}"
        Inline: true
    Footer: "Veranderd in {status} door: {changed-by-tag}"
    Thumbnail: "{user-pfp}"
    Timestamp: true
  IP:
    Author: "Server IP"
    Description: "Our Minecraft server's IP is **play.example.com**. Feel free to join!"
    AuthorIcon: "https://pscube.com/wp-content/uploads/2017/06/24-1024x1024.jpg"
  ApplicationCreated:
    Title: "Sollicitatie"
    Description: "{user-mention}, dank u voor het aanmaken van een sollicitatie. Vul deze vragen in en ons team zal uw aanvraag zo snel mogelijk bekijken."
  ApplicationPosition:
    Title: "Positie"
    Description: "Voor welke functie wilt u solliciteren? De huidige posities zijn {positions}"
  ApplicationComplete:
    Title: "Sollicitatie Afgerond"
    Description: "Uw aanvraag is compleet. Een personeelslid zal het bekijken en zo snel mogelijk een beslissing nemen."
  BugReported:
    Title: "🐛 Bug gemeld"
    Description: "Bedankt voor het melden van de bug! Onze ontwikkelaars zullen zo snel mogelijk naar het probleem kijken."
    Timestamp: true
  PendingBugreport:
    Title: "Bug rapport | In afwachting van goedkeuring"
    Fields:
      - Name: "Bug"
        Value: "{bug}"
        Inline: true
      - Name: "van"
        Value: "{user-mention}"
        Inline: true
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Bugreport:
    Title: "Bug rapport | {status}"
    Fields:
      - Name: "Bug"
        Value: "{bug}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "van"
        Value: "{user-mention}"
        Inline: true
      - Name: "Reden"
        Value: "{reason}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
    Footer: "Veranderd in {status} door: {changed-by-tag}"
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Ping:
    - Title: ":signal_strength: Bot Ping"
      Fields:
        - name: "API Latency"
          value: "{api-ping} ms"
      Timestamp: true
    - Title: ":signal_strength: Bot Ping"
      Fields:
        - name: "API Latency"
          value: "{api-ping} ms"
          inline: true
        - name: "Bot Latency"
          value: "{bot-ping} ms"
          inline: true
      Timestamp: true
  CategorizedHelp:
    Footer: "{bot-displayname}"
    FooterIcon: "{bot-pfp}"
    Timestamp: true
    Description: "Gebruik `-help command <command name>` om een specifiek commando op te zoeken"
    Fields:
      - name: ":earth_americas: Algemeen"
        value: "{prefix}help module general"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":tickets: Tickets"
        value: "{prefix}help module tickets"
        inline: true
      - name: ":coin: Munten"
        value: "{prefix}help module coins"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":sparkles: XP"
        value: "{prefix}help module xp"
        inline: true
      - name: ":pick: Minecraft"
        value: "{prefix}help module minecraft"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":video_game: Fun"
        value: "{prefix}help module fun"
        inline: true
      - name: ":musical_note: Muziek"
        value: "{prefix}help module music"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":dividers: Andere"
        value: "{prefix}help module other"
        inline: true
  CategorizedStaffHelp:
    Footer: "{bot-displayname}"
    FooterIcon: "{bot-pfp}"
    Timestamp: true
    Description: "Gebruik `-shelp commando <command name>` om een specifiek commando op te zoeken"
    Fields:
      - name: ":cop: Moderatie "
        value: "{prefix}staffhelp module moderation"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":tools: Admin"
        value: "{prefix}staffhelp module admin"
        inline: true
      - name: ":tada: Winactie"
        value: "{prefix}staffhelp module giveaways"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":desktop: Management"
        value: "{prefix}staffhelp module management"
        inline: true
  LevelUp:
    Title: "⬆️ Niveau omhoog"
    Description: "{user-mention}, je bent net een level omhoog gegaan! Je bent nu level **{level}**! {reward}"
  DMWelcome:
    Description: "Welkom op de server!"
  Banned:
    Title: "Verbannen"
    Description: "Je bent verbannen uit de **{server-name}** discord!"
    #Thumbnail: "https://www.youtube.com/watch?v=WKEciBi3BtQ"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Verbannen door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reden"
        Value: "{reason}"
  UserBanned:
    Title: ":anger: Gebruiker Verbannen"
    Description: "{user-mention} ({user-id}) is verbannen door {executor-mention} met de reden `{reason}`"
    Color: "#f52c2c"
    Timestamp: true
  Kicked:
    Title: "Er uit geschopt"
    Description: "Je bent uit de **{server-name}** discord gegooit. Je kan terug komen door een invite te krijgen !"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reden"
        Value: "{reason}"
  UserKicked:
    Title: "👞 Gebruiker er uit geschopt"
    Description: "{user-mention} is uit de server gegooit door {executor-mention} met de reden `{reason}`"
    Color: "#fc9803"
    Timestamp: true
  Muted:
    Title: "Gedempt"
    Description: "Je bent gedempt in de **{server-name}** discord.!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reden"
        Value: "{reason}"
  UserMuted:
    Title: "🔇 Gebruiker gedempt"
    Description: "{user-mention} is gedempt door {executor-mention} met als reden `{reason}`"
    Color: "#1c1c1c"
    Timestamp: true
  Tempbanned:
    Title: "Tijdelijk verbannen"
    Description: "Je bent tijdelijk verbannen van de **{server-name}** discord!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reden"
        Value: "{reason}"
      - Name: "Einddatum"
        Value: "<t:{timestamp}:f> (<t:{timestamp}:R>)"
  UserTempbanned:
    Title: ":anger: Gebruiker tijdelijk verbannen"
    Description: "{user-mention} ({user-id}) is tijdelijk verbannen door {executor-mention} met als reden `{reason}` tot <t:{timestamp}:f> (<t:{timestamp}:R>)"
    Color: "#f52c2c"
    Timestamp: true
  Tempmuted:
    Title: "Tijdelijk gedempt"
    Description: Je bent tijdelijk gedempt in de **{server-name}** server!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reden"
        Value: "{reason}"
      - Name: "Einddatum"
        Value: "<t:{timestamp}:f> (<t:{timestamp}:R>)"
  UserTempmuted:
    Title: "🔇 Gebruiker Tijdelijke gedempt"
    Description: "{user-mention} is tijdelijke gedempt door {executor-mention} met als reden `{reason}` tot <t:{timestamp}:f> (<t:{timestamp}:R>)"
    Color: "#1c1c1c"
    Timestamp: true
  Blacklisted:
    Title: "Geblokkeerd"
    Description: "Je bent geblokkeerd om een commando uit te voeren in de **{server-naam}** discord!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Commando"
        Value: "{command}"
      - Name: "door"
        Value: "{executor-mention} ({executor-tag})"
  UserBlacklisted:
    All:
      Title: "🛑 Gebruiker geblokkeerd"
      Description: "{user-mention} is nu geblokkeerd om **geen enkele** command uit tevoeren van deze bot."
      Timestamp: true
      Color: "#f52c2c"
    Command:
      Title: "🛑 User Blacklisted"
      Description: "{user-mention} is geblokkeerd om het volgende command `{command}` uit tevoeren"
      Timestamp: true
      Color: "#f52c2c"
  UserUnbanned:
    Title: "☑️ Gebruiker geunbanned"
    Description: "{user-mention} ({user-id}) is geunbanned door {executor-mention}"
    Timestamp: true
  Unblacklisted:
    Title: "Gedeblokkeerd"
    Description: "Je bent gedeblokkeerd om commando's uittevoeren in de **{server-name}** discord! (Dit betekent dat je weer commands kan uitvoeren)"
    Timestamp: true
    Color: "#25de1f"
    Fields:
      - Name: "Command"
        Value: "{command}"
      - Name: "Door"
        Value: "{executor-mention} ({executor-tag})"
  Unmuted:
    Title: "Ongedempt"
    Description: "Je bent niet meer gedempt in de **{server-name}** discord!"
    Timestamp: true
    Color: "#25de1f"
    Fields:
      - Name: "door"
        Value: "{executor-mention} ({executor-tag})"
  UserUnmuted:
    Title: "🔊 Gebruiker Ongedempt"
    Description: "{user-mention} is niet meer gedempt door {executor-mention}"
    Timestamp: true
  Warned:
    Title: "⚠️Uh oh! Je bent gewaarschuwd!"
    Description: "Je werd gewaarschuwd in de **{server-name}** discord!"
    Timestamp: true
    Color: "#fc9803"
    Fields:
      - Name: "Reden"
        Value: "{reason}"
      - Name: "Door"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Waarschuwing ID"
        Value: "{warning-id}"
      - Name: "Waarschuwing telling"
        Value: "{warning-count}"
  UserWarned:
    Title: "⚠️ Gebruiker gewaarschuwd"
    Description: "{user-mention} is gewaarschuwd door {executor-mention} met als reden `{reason}`"
    Color: "#fc9803"
    Timestamp: true
  UserAutoPunished:
    Title: "❗ Te veel waarschuwingen"
    Description: "{user-mention} heeft bereikt **{warning-count} waarschuwingen**, dus werden ze automatisch {punishment} {extra}"
    TempPunishExtraInfo: "({length})"
  Giveaway:
    Title: ":gift: Winactie"
    Description: "{description}"
    Fields:
      - Name: "Prijs"
        Value: "{prize}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Aantal Winnaars"
        Value: "{winners}"
        Inline: true
      - Name: "Gepresenteerd door"
        Value: "{host}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Winactie eindigt"
        Value: "{time-left}"
        Inline: true
      - Name: "\u200b"
        Value: "**Reageer met de :tada: emoji om mee te doen!**\n\n{extra-entries}"
        Inline: false
    Footer: "Eindigt op"
    Timestamp: true
  GiveawayWithRequirements:
    Title: ":gift: Winactie"
    Description: "{description}"
    Fields:
      - Name: "Prijs"
        Value: "{prize}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Aantal Winnaars"
        Value: "{winners}"
        Inline: true
      - Name: "Gepresenteerd door"
        Value: "{host}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Winactie eindigt"
        Value: "{time-left}"
        Inline: true
      - Name: "Requirements"
        Value: |-
          {requirements-coins}{requirements-xp}{requirements-level}{requirements-server}{requirements-roles-cant-have}{requirements-roles-must-have}{requirements-messages}

          **Reageer met de :tada: emoji om mee te doen!**

          {extra-entries}
        Inline: false
    Footer: "Eindigt op"
    Timestamp: true
  GiveawayEnded:
    Title: ":gift: Winactie beëindigd"
    Fields:
      - Name: "Prijs"
        Value: "{prize}\n{description}"
        Inline: true
      - Name: "Gepresenteerd door"
        Value: "{host}"
        Inline: true
      - Name: "De winnaars"
        Value: "{winners}"
        Inline: true
      - Name: "\u200b"
        Value: ":tada: **Maak een ticket om je prijs te claimen! Doe dit binnen 24 uur.**"
        Inline: false
    Timestamp: true
    Footer: "Beëindigd"
  Reminder:
    Title: "⏰ Herinner"
    Description: "Hey {user-mention}, vergeet dit niet!"
    Fields:
      - Name: "🗒️ Uw Herinnering:"
        Value: "{reminder}"
    Timestamp: true
  JoinVoiceChannel:
    Title: Gebruiker verbindt Kanaal
    Fields:
      - name: Kanaal
        value: "{channel-name} ({channel-id})"
      - name: Gebruiker
        value: "{user-mention} ({user-id})"
      - name: Gebruiker Tag
        value: "{user-tag}"
      - name: Tijd
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  LeaveVoiceChannel:
    Title: Gebruiker uit Kanaal
    Fields:
      - name: Kanaal
        value: "{channel-name} ({channel-id})"
      - name: Gebruiker
        value: "{user-mention} ({user-id})"
      - name: Gebruiker Tag
        value: "{user-tag}"
      - name: Tijd
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  SwitchVoiceChannel:
    Title: Gebruiker verwisseld Kanaal
    Fields:
      - name: Oud kanaal
        value: "{old-channel-name} ({old-channel-id})"
      - name: Nieuw kanaal
        value: "{new-channel-name} ({new-channel-id})"
      - name: Gebruiker
        value: "{user-mention} ({user-id})"
      - name: Gebruiker Tag
        value: "{user-tag}"
      - name: Tijd
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  TestEmbed:
    Title: "This is a test embed for the buttons.yml"
    Components:
      - [ "custombutton_test_button" ]
  Msgtop:
    Title: "📩 Verzonden berichten Leaderboard (Pagina {current-page}/{max-pages})"
    Footer: "Totaal verzonden berichten: {total_messages}"
  VCtop:
    Title: "🔊 Spreektijd Leaderboard (Pagina {current-page}/{max-pages})"
    Footer: "Totale tijd doorgebracht in VC: {total_time}"